
//FASHIONS
export const ADD_FASHIONS = 'ADD_FASHIONS';
export const FASHIONS_LOADING = "FASHIONS_LOADING";
export const FASHIONS_FAILED = "FASHIONS_FAILED";

//MOBILES
export const ADD_MOBILES = "ADD_MOBILES";
export const MOBILES_LOADING = "MOBILES_LOADING";
export const MOBILES_FAILED = "MOBILES_FAILED";

//ElECTRONICS
export const ADD_ElECTRONICS = "ADD_ElECTRONICS";
export const ElECTRONICS_LOADING = "ElECTRONICS_LOADING";
export const ElECTRONICS_FAILED = "ElECTRONICS_FAILED";

//APPLIANCES
export const ADD_APPLIANCES = "ADD_APPLIANCES";
export const APPLIANCES_LOADING = "APPLIANCES_LOADING";
export const APPLIANCES_FAILED = "APPLIANCES_FAILED";

//GROCERIES
export const ADD_GROCERIES = "ADD_GROCERIES";
export const GROCERIES_LOADING = "GROCERIES_LOADING";
export const GROCERIES_FAILED = "GROCERIES_FAILED";


 //users
export const FIND_USER = "FIND_USER"
export const USER_LOADING = "USER_LOADING"
export const USER_FAILED = "USER_FAILED"

